jupyter-incubator/declarativewidgets_explorer

bower.json
multi-select-menu.html
urth-viz-query.html

[Issue 14] Add multi select element used in group-by

---

urth-viz-explorer.html

migrate to abstract types jupyter-incubator/declarativewidgets#426

---

urth-viz-query.html

[Issue 5] Add spacing between aggregations

---

Makefile

also removed running container name so we don't have to keep deleting it when re-running

Mount folder into urth_components to ease dev

---

elements/urth-viz-explorer.html

[Issue 22] Fix explorer styling for wide charts/table

---

urth-viz-explorer.html

[Issue 31] Add value changed handler to dataframe element in template

---

urth-viz-explorer.html

avoid exception for type=table fixes #29

---

notebooks/examples/urth-viz-explorer.ipynb
urth-viz-explorer.html

[Issue 26] Set explorer selection based on table selection

---

urth-viz-explorer.html

update type with field name Fixes #30

---

urth-viz-explorer.html
urth-viz-query.html

Fixes #33 (better handling of default selections) #44 (query update regression) #45 (`limit` regression)
@dalogsdon

Ref dataframe

---

bower.json
urth-viz-explorer.html

[Issue 12] Added dialog to edit the Vega JSON.

---

urth-viz-query.html

filter to show aggregate columns of type Number only. Fixes #47

---

notebooks/demos/taxi/taxi-selection.ipynb
notebooks/demos/taxi/taxi.ipynb
notebooks/examples/urth-viz-explorer.ipynb

need select-as-object branch on declarativewidgets

update to use new explore function signature, selection-as-object

---

urth-viz-explorer.html
urth-viz-vega.html

Fixes #3  Requires vega-lite 1.2.0 or later

Pass size to vega, trigger resize

---

multi-select-menu.html

[Issue 54] Add 'selected' property to set selected items in  multi-select-menu.

---

paper-card-collapse.html
urth-viz-explorer.html
urth-viz-query.html

[Issue 42] Create groups and filters in any order

---

multi-select-menu.html

[Issue 67] Fix multi-select-menu item selection when list is filtered.

---

urth-viz-explorer.html

avoid duplicate x/y settings

---

README.md
urth-viz-explorer.html
urth-viz-query.html

Provide usage documentation #61

---

multi-select-menu.html
urth-viz-query.html

[Issue 63] Reset query columns when a group-by or agg changes.

---

bower.json
urth-viz-query.html

add sorting capability

---

urth-viz-query.html

Ensure sort direction still works since I had to change the data to boolean for toggle button.

Style sort elements.

---

urth-viz-explorer.html

add optional flag and associated clear action

---

multi-select-menu.html
notebooks/demos/taxi/taxi-selection.ipynb
notebooks/demos/taxi/taxi.ipynb
notebooks/examples/urth-viz-explorer.ipynb
paper-card-collapse.html
urth-viz-explorer.html
urth-viz-query.html

[Issue 77] Minor styling fixes

---

urth-viz-query.html

[Issue 83] Wait for query widget to finish "initializing" before updating queries

---

multi-select-menu.html
urth-viz-explorer.html
urth-viz-query.html

Paired with @peller to resolve #89

Clear group-by selector

---

urth-viz-query.html

mark some properties as @private Fixes #93

---

urth-viz-query.html

fix regression from cc9977, reference to data-query-index #89
